const About = () => {
    return (
        <div className="container mx-auto">
            <h2 className="text-center text-3xl font-semibold mt-2">About</h2>
            <p className="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam odio numquam modi rem perspiciatis, commodi ipsa recusandae perferendis cum facere at! Debitis, cumque distinctio explicabo itaque, nesciunt asperiores vel omnis hic eos ipsam sed doloremque voluptates labore fugit reprehenderit magni dignissimos autem ratione minima! Soluta quam nostrum incidunt. Ipsam, voluptas corporis placeat tempore quas cum repellendus, qui hic mollitia dolores maxime facilis exercitationem eum. Laudantium omnis consequatur provident nemo facilis, tenetur quam voluptates amet minima atque repudiandae sint labore pariatur modi maiores vero veniam reiciendis assumenda, ullam, voluptatibus aperiam eos cum. Voluptates totam quidem itaque officia architecto labore quos quibusdam? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ullam consequatur tempora soluta eos veritatis, quam itaque doloremque mollitia, harum corporis autem quae odit minima in numquam, porro doloribus vitae possimus ea officiis sequi! Officia quisquam praesentium veritatis placeat illum expedita et nihil, a, fugit dolorem atque adipisci at voluptate cupiditate reprehenderit suscipit ipsa doloremque officiis aut voluptatem alias iure ut obcaecati consequatur? Consequatur culpa minima, labore, sunt facilis consequuntur adipisci sit minus, mollitia magnam qui. Dolore hic pariatur eos deleniti fuga qui tempore voluptate dolores adipisci sunt nobis, autem voluptatibus nulla eligendi ab nesciunt quisquam. Totam laudantium modi minima laboriosam praesentium iste sapiente eligendi, consectetur iure, qui repellendus voluptatum explicabo. Magnam, veritatis. Possimus facilis in architecto cum dolorem perspiciatis vel qui a dolore! Magni et odio molestiae. Nam atque vel magni itaque culpa eligendi doloremque, molestiae soluta dolores. Incidunt architecto accusantium mollitia nobis ullam aliquid. Assumenda, eligendi illum consequuntur atque aperiam, quasi cum tenetur unde dicta autem totam hic eveniet inventore tempora consectetur porro accusamus voluptatem ipsam maiores laudantium vitae magni ea. Dicta, animi beatae. Quasi, aut non facilis atque ad quisquam veritatis, consequatur laborum maiores, temporibus perspiciatis vel minima harum blanditiis debitis sit suscipit a? Debitis, neque voluptatem! Ab.</p>
        </div>
    )
}

export default About